services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.pgvector
    image: semearch/pgvector:pg18
    container_name: postgres-pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: semsearch
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
volumes:
  postgres_data:
